ministryofjustice/hmpps-adjustments-api

README.md, build.gradle.kts, docker-compose-test.yml, run-local.sh, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/entity/Adjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/entity/UnlawfullyAtLarge.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/enums/UnlawfullyAtLargeType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/AdjustmentDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/UnlawfullyAtLargeDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdjustmentsService.kt, src/main/resources/migration/common/V4__unlawfully_at_large.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/controller/AdjustmentControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/controller/LegacyAndAdjustmentsControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/ValidationServiceTest.kt
Also added a `run-local` and `docker-compose` file for running the the db locally and the api via spring boot
=> ADJUST1-108 Create a UAL Adjustment - new 1-to-1 table and associated functionality

src/main/resources/migration/common/V5__replace_postgres_enum_cols.sql
3rd time lucky.
Just defaulting the columns so we wont need to do a full migration again.
=> ADJUST1-112 Replace columns.

src/main/resources/migration/postgres/V10__postgres_migration.sql
The JSON psql query treats everything as a string.
=> Fixing flyway migration script.

helm_deploy/hmpps-adjustments-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/client/SystemPrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/service/LegacyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/listener/HMPPSDomainEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/listener/PrisonerEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/listener/SQSMessage.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/respository/AdjustmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonerInOutService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/integration/SqsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/listener/PrisonerListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/wiremock/HmppsAuthMockServer.kt, src/test/resources/application-test.yml
Queue and Auth Secret now have been created.
=> ADJUST1-379 handle booking released and admission events.

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/enums/InterceptType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/AdaIntercept.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedServiceTest.kt
Unit tests have been copied from the equivalent unit tests in the UI + a couple of extra ones
=> CMG-36 Add Unit tests for the intercept logic which has been copied from the UI

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/listener/PrisonerEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdjustmentsEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt
The bulk comparison testing effectively ran the UI code and the new API code against prisoners in dev and checked that the same results appeared for the intercept
=> CMG-36 Fixes to the interept logic (which was copied from the UI)  after bulk comparison testing was performed in dev

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt
https://dsdmoj.atlassian.net/browse/ADJST-749
=> Filter out PADAs where Only Active Licence Recall Sentences Present

src/main/resources/migration/postgres/V27__set_period_of_custody_and_status.sql
This script migrated existing data, however it took too long. I will run the migrations manually.
On dev (there is nearly double the data on prod):
UPDATE 477321
Time: 394741.066 ms (06:34.741)
UPDATE 110692
Time: 67979.217 ms (01:07.979)
UPDATE 613853
Time: 170589.305 ms (02:50.589)
=> Remove long running script.

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/enums/InterceptType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/additionaldays/AdaIntercept.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/controller/AdaAdjudicationControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt
This is _`**NOT BACKWARD COMPATIBLE**`_. The associated Front end change must also be promoted.
https://github.com/ministryofjustice/hmpps-adjustments/pull/459
=> Code to align APIs for TECH ANALYSIS 1 in ADJST-953

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/enums/InterceptType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/additionaldays/AdaIntercept.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/controller/AdaAdjudicationControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt
Reverts ministryofjustice/hmpps-adjustments-api#235
=> Revert "Code to align APIs for TECH ANALYSIS 1 in ADJST-953"

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/enums/InterceptType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/additionaldays/AdaIntercept.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/controller/AdaAdjudicationControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt
Reverts ministryofjustice/hmpps-adjustments-api#239
=> Revert "Revert "Revert "Code to align APIs for TECH ANALYSIS 1 in ADJST-953"""

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/enums/InterceptType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/additionaldays/AdaIntercept.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/controller/AdaAdjudicationControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt
Reverts ministryofjustice/hmpps-adjustments-api#241
Please promote the associated frontend changes with this backend change.
Latest FE should be ok.
=> Revert "Revert "Revert "Revert "Code to align APIs for TECH ANALYSIS 1 in ADJST-953""""

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/service/LegacyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonerEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/listener/PrisonerListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/wiremock/PrisonApiMockServer.kt
https://dsdmoj.atlassian.net/browse/ADJST-1008
=> setCurrentTerm correctly by getting it through PrisonAPI service call

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/entity/Adjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/entity/AdjustmentType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/entity/TimeSpentAsAnAppealApplicant.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/model/LegacyAdjustmentType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/service/LegacyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/AdjustmentDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/TimeSpentAsAnAppealApplicantDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/ValidationCode.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdjustmentsTransactionalService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/ValidationService.kt, src/main/resources/migration/common/V28__time_spent_as an_appeal_applicant.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/controller/AdjustmentControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/controller/LegacyAndAdjustmentsControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/UnusedDeductionsEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/ValidationServiceTest.kt, src/test/resources/test_data/reset-data.sql
=> ADJST-983 Add time spent as an appeal applicant adjustment type

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/client/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/client/PrisonerSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/service/LegacyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/prisonersearchapi/Prisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAwardedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdjustmentsTransactionalService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonerEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdditionalDaysAddedServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/wiremock/PrisonerSearchApiMockServer.kt, src/test/resources/application-test.yml
https://dsdmoj.atlassian.net/browse/ADJST-816
=> Move from PrisonAPI to PrisonerSearchAPI for Prisoner Search

helm_deploy/values-prod.yaml
Looks like Adjustments is having issues with restore because v14 isn't supported by the latest version of the restore image. I'll try fixing the version, and I'll raise tickets for adjustments to upgrade the db.
=> Fixing postgresql restore.

helm_deploy/values-prod.yaml
Reverts ministryofjustice/hmpps-adjustments-api#263
=> Revert "Fixing postgresql restore."

helm_deploy/hmpps-adjustments-api/Chart.yaml
Reverts ministryofjustice/hmpps-adjustments-api#261
=> Revert "Update Helm release generic-service to 3.11"

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/client/RemandAndSentencingApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/SentenceInfo.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/remandandsentencing/RecallType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/model/remandandsentencing/SentenceDetailResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/AdjustmentsTransactionalService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/SentenceInfoService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/service/PrisonServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/wiremock/RemandAndSentencingApiMockServer.kt
https://dsdmoj.atlassian.net/browse/ADJST-468
=> ADJST-468 Move from hardcoding to rass for sentence info

helm_deploy/hmpps-adjustments-api/values.yaml
https://dsdmoj.atlassian.net/browse/ADJST-468
=> Fix the failing pipeline

src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/controller/LegacyController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/service/LegacyService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/adjustments/api/legacy/controller/LegacyAndAdjustmentsControllerIntTest.kt
https://dsdmoj.atlassian.net/browse/ADJST-1062
=> ADJST-1062 Remove Sync logic as Nomis is in readonly mode for adjustments

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
https://dsdmoj.atlassian.net/browse/ADJST-1278
=> ADJST-1278 Correct the SA for data analytics extractor for Adjustments app across env
